### ISSUE TITLE
FirstLogonCommands requires user to login to VM to run the script - So  how does winrm configured automatically here?

### ISSUE THREAD

**Issue by naveenreddy4955** [claranet/terraform-azurerm-windows-vm#1]
additional_unattend_content {
    setting = "FirstLogonCommands"
    content = file(format("%s/files/FirstLogonCommands.xml", path.module))
  }
  
  https://docs.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-shell-setup-firstlogoncommands
  
 Please let me know if any of you have the same issue

**Comment by BzSpi** [comment]
Hello @naveenreddy4955 

I don't understand exactly what is the issue here. 
WinRM is not installed when creating your VM instance ? Can you provide yuor Terraform code ?
