### ISSUE TITLE
[DOC] Missing example creating vm_admins_group and vm_users_group 

### ISSUE THREAD

**Issue by mloskot** [claranet/terraform-azurerm-windows-vm#2]
### Description

The example refers to AAD groups 

https://github.com/claranet/terraform-azurerm-windows-vm/blob/697f7e89110ceaa905953d57f13c3a5d76da8d9c/README.md?plain=1#L248-L254

but there is no explanation those are user-defined groups and not pre-existing groups. This makes it not a self-contained example.

The example should include code creating the groups and adding to it e.g. `data.azurerm_client_config.current.object_id` or there should be comment the example assumes  those group pre-exist, so user knows they need to create it.

**Comment by Shr3ps** [comment]
Thanks, internal fix MR opened :)

**Comment by mloskot** [comment]
Thank you!
